version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "3300:3300"
    environment:
      POSTGRES_URL: jdbc:postgresql://localhost:5432/muca_tour
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - microservices_muca_tour:/var/lib/postgres

volumes:
  microservices_muca_tour: